// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgHyHQlI0pD2phXdKec-YNrSF3HuMAfXA',
    appId: '1:546669813629:web:c7d77bbfaee2165578f614',
    messagingSenderId: '546669813629',
    projectId: 'fypsttfb',
    authDomain: 'fypsttfb.firebaseapp.com',
    storageBucket: 'fypsttfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC932gRCsQ1gk5988j0CLcv1u5dXmQOyGA',
    appId: '1:546669813629:android:ea2c7051ddeec3ac78f614',
    messagingSenderId: '546669813629',
    projectId: 'fypsttfb',
    storageBucket: 'fypsttfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAaK4XRY-zQBc0JLuT_CKTKGWtUah0oUk',
    appId: '1:546669813629:ios:c5d2104f94aeeb6f78f614',
    messagingSenderId: '546669813629',
    projectId: 'fypsttfb',
    storageBucket: 'fypsttfb.appspot.com',
    iosBundleId: 'com.trancriber.lugandastt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAaK4XRY-zQBc0JLuT_CKTKGWtUah0oUk',
    appId: '1:546669813629:ios:14e80df3728b607d78f614',
    messagingSenderId: '546669813629',
    projectId: 'fypsttfb',
    storageBucket: 'fypsttfb.appspot.com',
    iosBundleId: 'com.trancriber.lugandastt.RunnerTests',
  );
}
